name: libsql_dart
description: "LibSQL Dart client library to interact with LibSQL/Turso database instance."
version: 0.2.0
homepage:
repository: https://github.com/dikatok/libsql_dart
issue_tracker: https://github.com/dikatok/libsql_dart/issues

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.2.0
  freezed_annotation: ^2.4.4
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.12

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
